# Generated by Django 5.0.3 on 2024-04-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
                ("user_email", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "Users",
            },
        ),
    ]
